.\" The MIT License (MIT)
.\"
.\" Copyright (c) 2019 Vincent Davis
.\" <vincedav2495@gmail.com>
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
.\" THE SOFTWARE.
.\" %%%LICENSE_END
.\"
.TH WLU_INIT_VK 3 "29 June 2019" "1.0" "WLU_INIT_VK Man Page"
.SH NAME
wlu_init_vk \- This will return a pointer the vkcomp

.SH SYNOPSIS
.nf
.B #include <wlu/vkall.h>
.PP
.BR "" struct " vkcomp *wlu_init_vk()"
.fi
.PP
.nf
.pp
.SH DESCRIPTION
.PP
The
.BR wlu_init_vk()
function returns a pointer to a vkcomp struct with above elements viewable in
.BR wlu_vkall.h(3)
.
.SH EXAMPLE WLU_INIT_VK
.EE
.in
.SS Program source
\&
.EX
#include <wlu/vkall.h>

int main() {
  vkcomp *app = wlu_init_vk();
  wlu_freeup_vk(app);
  return 0;
}
.EE

.SH SEE_ALSO
.B "wlu_freeup_vk(3)"

.SH AUTHOR
Vincent Davis (vincedav2495@gmail.com)
